Set the last contribution value if exists
hassyyy/WCoT-Dashboard pull request #3
Opened 2020-10-04 18:42 UTC by Snick555

Issue https://github.com/hassyyy/WCoT-Dashboard/issues/1

2020-10-16 19:45 UTC, hassyyy requested changes

2020-10-16 19:45 UTC, hassyyy commented on app/controllers/users_controller.rb
> +    @new_contribution = current_user.contributions.build(value: @user.contributions.last.try(:value))
Contributions are scoped in descending order. Hence the last value will be the oldest. We need the latest value. 
Anyway, let's use `@previous_contributions` itself to avoid another query
```suggestion
    @new_contribution = current_user.contributions.build(value: @previous_contributions.first.try(:value))
```

2020-10-17 09:14 UTC, Snick555 commented on app/controllers/users_controller.rb
> +    @new_contribution = current_user.contributions.build(value: @user.contributions.last.try(:value))
@hassyyy changed

2020-10-17 10:40 UTC, hassyyy approved these changes

2020-10-17 10:40 UTC, merged

2020-10-17 10:41 UTC, hassyyy commented
@Snick555 Thanks for your contribution :)